<?php require_once './templates/blocs/header.phtml'; ?>

<div class="container-fluid">
    <div class="row">
        <div class="col">
            <table class="table table-striped table-hover table-sm">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Code</th>
                        <th>Nom</th>
                        <th>Nom (Capitales)</th>
                        <th>SLUG</th>
                        <th>Soundex</th>
                        <th>Soundex attendu</th>
                        <th>E.mail</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($departments as $department) : ?>
                    <tr class="<?=$department['css-class']?>">
                        <td class=""><?=$department['id']?></td>
                        <td class="<?=$department['col-classes']['code']?>"><?=$department['code']?></td>
                        <td class="<?=$department['col-classes']['name']?>"><?=$department['name']?></td>
                        <td class="<?=$department['col-classes']['uppercase']?>"><?=$department['uppercase_name']?></td>
                        <td class="<?=$department['col-classes']['slug']?>"><?=$department['slug']?></td>
                        <td class="<?=$department['col-classes']['soundex']?>"><?=$department['soundex']?></td>
                        <td class=""><?=$department['expected_soundex']?></td>
                        <td class="<?=$department['col-classes']['email']?>"><?=$department['email']?></td>
                    </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?php require_once './templates/blocs/footer.phtml'; ?>


